=== Livda/WorkHard/5INFO/BDA/tpXML2/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="carnetDAdresse">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="carteDeVisite" maxOccurs="unbounded">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element name="prenom" type="xsd:string"></xsd:element>
                    <xsd:element name="nom" type="xsd:string"></xsd:element>
                    <xsd:element name="organisme" type="xsd:string"></xsd:element>
                    <xsd:element name="adresse">
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element name="numero" type="xsd:string"></xsd:element>
                                <xsd:element name="voie">
                                <xsd:complexType>
                                <xsd:simpleContent>
                                    <xsd:extension base="xsd:string">
                                    <xsd:attribute name="type" type="voie" default="rue"></xsd:attribute>
                                    </xsd:extension>
                                </xsd:simpleContent>
                                </xsd:complexType>
                                </xsd:element>
                                <xsd:element name="ville">
                                    <xsd:complexType>
                                    <xsd:simpleContent>
                                        <xsd:extension base="xsd:string">
                                        <xsd:attribute name="codepostal" type="codePostal"></xsd:attribute>
                                    </xsd:extension>
                                    </xsd:simpleContent>
                                    </xsd:complexType>
                                </xsd:element>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="note" minOccurs="0">
                        <xsd:complexType mixed="true">
                            <xsd:sequence>
                                <xsd:element name="cle" type="xsd:string"/>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>
                </xsd:sequence>
            <xsd:attribute name="id" type="xsd:ID" use="required"></xsd:attribute>
            </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    </xsd:element>
    <xsd:simpleType name="codePostal">
        <xsd:restriction base="xsd:integer">
            <xsd:pattern value="[0-9]{5}"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="voie">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="rue"/>
            <xsd:enumeration value="avenue"/>
            <xsd:enumeration value="impasse"/>
            <xsd:enumeration value="cours"/>
            <xsd:enumeration value="square"/>
            <xsd:enumeration value="boulevard"/>
            <xsd:enumeration value="chemin"/>
            <xsd:enumeration value="allee"/>
            <xsd:enumeration value="quai"/>
            <xsd:enumeration value="route"/>
            <xsd:enumeration value="passage"/>
            <xsd:enumeration value="place"/>
            <xsd:enumeration value="rondPoint"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== Livda/WorkHard/5INFO/BDA/tpXML2/carnetadr.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<carnetDAdresse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
	<carteDeVisite id="i1">
		<prenom>Yves</prenom>
		<nom>Merci</nom>
		<organisme>Vins en vrac Cie</organisme>
		<adresse>
			<numero>40</numero>
			<voie type="avenue">general Leclerc</voie>
			<ville codepostal="45042">Orleans</ville>
		</adresse>
		<note> Très grand <cle>champagne</cle> </note>
	</carteDeVisite>
	<carteDeVisite id="i2">
		<prenom>Roland</prenom>
		<nom>Grand</nom>
		<organisme>Artichauts et primeurs</organisme>
		<adresse>
			<numero>256</numero>
			<voie type="boulevard">Martenot</voie>
			<ville codepostal="35000">Rennes</ville>
		</adresse>
	</carteDeVisite>
	<carteDeVisite id="i6">
		<prenom>Harold</prenom>
		<nom>Lejean</nom>
		<organisme>Fruits et legumes boutik</organisme>
		<adresse>
			<numero>256</numero>
			<voie>Martenot</voie>
			<ville codepostal="35000">Rennes</ville>
		</adresse>
		<note>Tous les <cle>fruits</cle> frais à volonte
		</note>
	</carteDeVisite>
	<carteDeVisite id="i3">
		<prenom>Pierre</prenom>
		<nom>Dupont</nom>
		<organisme>Cavavins</organisme>
		<adresse>
			<numero>1 bis</numero>
			<voie>La Rabine</voie>
			<ville codepostal="56000">Vannes</ville>
		</adresse>
	</carteDeVisite>
	<carteDeVisite id="i4">
		<prenom>Paul</prenom>
		<nom>Lapate</nom>
		<organisme>Laboulang'</organisme>
		<adresse>
			<numero>56</numero>
			<voie type="impasse">Dubout</voie>
			<ville codepostal="35400">Redon</ville>
		</adresse>
		<note>Les meilleurs <cle>croissants</cle> de Bretagne
		</note>
	</carteDeVisite>
	<carteDeVisite id="i5">
		<prenom>Jean</prenom>
		<nom>Passe</nom>
		<organisme>Cavavins</organisme>
		<adresse>
			<numero>56</numero>
			<voie type="boulevard">Leclerc</voie>
			<ville codepostal="29000">Brest</ville>
		</adresse>
	</carteDeVisite>
</carnetDAdresse>
